### What Question to ask first, to get overview of Data

In [31]:
import pandas as pd

df = pd.read_csv("../Data Gathering/Top_Rated_Movies.csv")

In [32]:
# How a big data is?

df.shape

(10000, 8)

In [33]:
# How does data look like??
df.sample(5)

,Unnamed: 0,id,title,overview,release_date,popularity,vote_average,vote_count
4513,4513,526050,Little,"Jordan Sanders, a take-no-prisoners tech mogul...",2019-04-04,2.3364,6.800,759
9019,9019,14648,Podium,Bernand Fréderic is a mediocre bank executive....,2004-02-11,1.8086,5.931,464
8674,8674,228968,Kidnapping Mr. Heineken,The true story of the kidnapping of Freddy Hei...,2015-03-12,2.0675,6.015,669
7466,7466,10743,Confidence,What Jake Vig doesn't know just might get him ...,2003-04-25,1.0631,6.272,483
8064,8064,31578,Body Bags,A horror anthology containing three stories: a...,1993-08-08,1.3467,6.100,386

In [34]:
# What is data type of cols?
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    10000 non-null  int64
 1   id            10000 non-null  int64
 2   title         10000 non-null  str
 3   overview      9998 non-null   str
 4   release_date  9997 non-null   str
 5   popularity    10000 non-null  float64
 6   vote_average  10000 non-null  float64
 7   vote_count    10000 non-null  int64
dtypes: float64(2), int64(3), str(3)
memory usage: 625.1 KB

In [35]:
# Are there a missing values?

df.isnull().sum()

Unnamed: 0      0
id              0
title           0
overview        2
release_date    3
popularity      0
vote_average    0
vote_count      0
dtype: int64

In [36]:
# How does data look like mathematically?
df.describe()

        Unnamed: 0            id    popularity  vote_average    vote_count
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000
mean    4999.50000  2.342017e+05      4.674263      6.767611   2130.461700
std     2886.89568  3.124208e+05     13.734988      0.635526   3407.610026
min        0.00000  2.000000e+00      0.008400      5.580000    300.000000
25%     2499.75000  1.039775e+04      1.938875      6.270000    477.750000
50%     4999.50000  4.284650e+04      2.936750      6.731000    876.500000
75%     7499.25000  4.172758e+05      4.724350      7.230250   2144.250000
max     9999.00000  1.632181e+06    706.736100      9.056000  40266.000000

In [37]:
# Are there any duplicate value exist?
df.duplicated().sum()

np.int64(0)

In [ ]:
# Correlation tells us how two columns move together.
# Value ranges from -1 to 1:
#   +1  -> Both columns increase together (e.g. more votes = more popular)
#   -1  -> One increases while other decreases (inverse relation)
#    0  -> No relation at all
# Rule of thumb:
#   0.0 - 0.3  -> Weak correlation
#   0.3 - 0.7  -> Moderate correlation
#   0.7 - 1.0  -> Strong correlation

# ex-
# If I see column A go up, can I predict whether column B will go up, go down, or do nothing?
# Imagine if movies with more votes became less popular — as one goes up, the other goes down. That's "moving opposite.
# If I see column A go up, can I predict whether column B will go up, go down, or do nothing?

df.corr(numeric_only=True)['popularity']

              Unnamed: 0        id  popularity  vote_average  vote_count
Unnamed: 0      1.000000  0.003355   -0.115757     -0.989908   -0.250952
id              0.003355  1.000000    0.130517      0.001170   -0.104184
popularity     -0.115757  0.130517    1.000000      0.135937    0.221981
vote_average   -0.989908  0.001170    0.135937      1.000000    0.279196
vote_count     -0.250952 -0.104184    0.221981      0.279196    1.000000